language: python
notifications:
  email: false

python:
  - "3.5"

env:
  - TEST_SUITE=nose-tests

matrix:
  include:
    - python: "3.5"
      env: TEST_SUITE=mypy-run PY_VERSION=3.5


install:
  - pip install -r requirements.txt

script:
  - ./travis/$TEST_SUITE.sh
